# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: myapp
#   name: myapp
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: myapp
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: myapp
#     spec:
#       containers:
#       - image: logicgod007/packages:1
#         name: myapp
#         resources: {}
# status: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: logicgod007/packages:1
          env:
            - name: DOCKER_USERNAME
              value: "logicgod007"
            - name: DOCKER_PASSWORD
              value: "Docker@250"

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: myapp
